#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Project : Broken Promises
# -----------------------------------------------------------------------------
# Author : Edouard Richard                                  <edou4rd@gmail.com>
# -----------------------------------------------------------------------------
# License : GNU General Public License
# -----------------------------------------------------------------------------
# Creation : 22-Nov-2013
# Last mod : 22-Nov-2013
# -----------------------------------------------------------------------------
# Run rw_worker in background and rq_scheduler_worker after
python Scripts/rq_worker.py &
echo "Launching rqscheduler"
python Scripts/rq_scheduler_worker.py
# EOF
